### PR TITLE
fix: to remove illegal characters

### PR DESCRIPTION
**Pull request by biorz**

### CODE REVIEW

**Comment by chrisgrieser** [comment]
Adding those parenthesis does not change anything about the script, or am I mistaken?

**Comment by biorz** [comment]
like `google.com/path`, due to the execution order, the value of `filename.slice(-1)`  is `oggle.com/path` before it is assigned, the final result is Google.com/path。

my English is not very good, you can try to run

**Comment by chrisgrieser** [comment]
ah, haven't thought of the execution order, you are right. Thanks!

**Comment by biorz** [comment]
I like this plugin, lots of features 🙏

**Pull request merged**
